### ISSUE TITLE
Is there a way to bypass NotImplementedError

### ISSUE THREAD

**Issue by DadongZ** [pysam-developers/pysam#1076]
I was trying to count coverage from a bam file and got NotImplementedError:

```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    depth = bamfile.count_coverage(chrom,pos_l,pos_r)
  File "pysam/libcalignmentfile.pyx", line 1580, in pysam.libcalignmentfile.AlignmentFile.count_coverage
  File "pysam/libcalignedsegment.pyx", line 1976, in pysam.libcalignedsegment.AlignedSegment.get_aligned_pairs
NotImplementedError: Padding (BAM_CPAD, 6) is currently not supported. Please implement. Sorry about that.
```
Is there a way to bypass the error?

**Comment by terrycojones** [comment]
@DadongZ this is now fixed.
