### ISSUE TITLE
Error ‘invalid option’ when using pysam.index after to pysam.depth

### ISSUE THREAD

**Issue by fescudie** [pysam-developers/pysam#1084]
Hello,

Below the description of the bug. Thanks in advance for your explanation/solution.

# Description

After using pysam.depth with the option ‘–s’, the following calls to pysam.index raise this exception: 

```
index: invalid option -- '�'
Traceback (most recent call last):
  File "test_index.py", line 26, in <module>
    pysam.index(tmp_bam)
  File "/home/user/Documents/code/project/venv/lib/python3.8/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]\nOptions:\n  -b       Generate BAI-format index for BAM files [default]\n  -c       Generate CSI-format index for BAM files\n  -m INT   Set minimum interval size for CSI indices to 2^INT [14]\n  -@ INT   Sets the number of threads [none]\n'
```

Note: The invalid character may change when the code is rerun.
No error is raised if I remove ‘-s’ option in pysam.depth.

# Pysam release

0.18.0

# Code to reproduce

```
import pysam
import os

tmp_bam = "/tmp/tmp.bam"
tmp_sam = "/tmp/tmp.sam"

# Write SAM
with open(tmp_sam, "w") as writer:
    writer.write("""@SQ	SN:chr1	LN:60
read1	0	chr1	1	60	34M	*	0	0	ATGACTGAATATAAACTTGTGGTAGTTGGAGCTG	*	NM:i:0	MD:Z:34	AS:i:34	XS:i:0
""")
# SAM to BAM
with pysam.AlignmentFile(tmp_sam, "r") as reader:
    with pysam.AlignmentFile(tmp_bam, "wb", header=reader.header) as writer:
        for record in reader:
            writer.write(record)
# Test
pysam.index(tmp_bam)
pysam.depth(
    "-a",
    "-r", "chr1:5-15",
    "-s",
    tmp_bam
)
os.remove(tmp_bam + ".bai")
pysam.index(tmp_bam)
```

**Comment by jmarshall** [comment]
Thanks for the test case. This fails on a call to `pysam.index()` (or several other subcommands) after other samtools commands have previously been run, due to incorrectly resetting `getopt()` parsing on Linux. #1085 will fix it.
