### ISSUE TITLE
pysam: htslib configure options: None

### ISSUE THREAD

**Issue by nurmians** [pysam-developers/pysam#1102]
I am trying to install pysam with:
```
export HTSLIB_CONFIGURE_OPTIONS=--disable-bz2
pip3 install pysam --user
```

And I am still getting the same error:
```
Either configure with --disable-bz2 (which will make some CRAM files
    produced elsewhere unreadable) or resolve this error to build HTSlib.
    Makefile:122: htscodecs.mk: No such file or directory
    config.mk:2: *** Resolve configure error first.  Stop.
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-md26g5cb/pysam/setup.py", line 376, in <module>
        htslib_make_options = run_make_print_config()
      File "/tmp/pip-build-md26g5cb/pysam/setup.py", line 74, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "/usr/lib64/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib64/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['make', '-s', 'print-config']' returned non-zero exit status 2.

```
Why is pysam htslib configure options still "None"?

**Comment by nurmians** [comment]
I was missing another library that had to be disabled at the same time:
`export HTSLIB_CONFIGURE_OPTIONS="--disable-bz2 --disable-lzma --disable-libcurl"`
