### ISSUE TITLE
configure: error: zlib development files not found.

### ISSUE THREAD

**Issue by yaping-cn** [pysam-developers/pysam#1127]
I am trying to build pysam 0.18.0 on centos 7 and it failed with this error.
```
checking for inflate in -lz... no
  configure: error: zlib development files not found

  HTSlib uses compression routines from the zlib library <http://zlib.net>.
  Building HTSlib requires zlib development files to be installed on the build
  machine; you may need to ensure a package such as zlib1g-dev (on Debian or
  Ubuntu Linux) or zlib-devel (on RPM-based Linux distributions) is installed.

  FAILED.  This error must be resolved in order to build HTSlib successfully.
  error in pysam setup command: use_2to3 is invalid.
  # pysam: htslib mode is shared
  # pysam: htslib configure options: None
  # pysam: could not configure htslib, choosing conservative defaults
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /root/software/anaconda3/conda-bld/pysam_1661561279809/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/root/software/anaconda3/conda-bld/pysam_1661561279809/work/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-kbdl4pft
  cwd: /root/software/anaconda3/conda-bld/pysam_1661561279809/work/
  Preparing metadata (setup.py): finished with status 'error'
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Exception information:
Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
    call_subprocess(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 341, in run
    requirement_set = resolver.resolve(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 291, in __init__
    super().__init__(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 161, in __init__
    self.dist = self._prepare()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _prepare
    dist = self._prepare_distribution()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 302, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 428, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 497, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/req/req_install.py", line 532, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
  File "$PREFIX/lib/python3.9/site-packages/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
Removed file://$SRC_DIR from build tracker '/tmp/pip-build-tracker-1nnwlvgq'
Removed build tracker: '/tmp/pip-build-tracker-1nnwlvgq'
Traceback (most recent call last):
  File "/root/software/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
    execute(sys.argv[1:])
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
    packages_from_this = build(metadata, stats,
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 2211, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/utils.py", line 411, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/root/software/anaconda3/lib/python3.9/site-packages/conda_build/utils.py", line 391, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/root/software/anaconda3/conda-bld/pysam_1661561279809/work/conda_build.sh']' returned non-zero exit status 1.
```
Any hints on what could be the problem?

**Comment by jmarshall** [comment]
The error message tells you how to fix this:

>  HTSlib uses compression routines from the zlib library \<http://zlib.net\>.
  Building HTSlib requires zlib development files to be installed on the build
  machine; you may need to ensure a package such as zlib1g-dev (on Debian or
  Ubuntu Linux) or **zlib-devel (on RPM-based Linux distributions)** is installed.

(Or, if you are using conda, you could install the `zlib` conda package in the environment in which you are building this.)

You should verify that you are indeed selecting pysam 0.18.0. This additional error should not appear when building 0.17.0 or later, as `use_2to3` no longer appears in _setup.py_:

> error in pysam setup command: use_2to3 is invalid.

You appear to be using conda, so you might consider just installing the pre-buit `pysam` package from the [bioconda channel](https://bioconda.github.io).
