### ISSUE TITLE
Renaming Chromosomes in vcf/bcf files

### ISSUE THREAD

**Issue by Lew619** [pysam-developers/pysam#1170]
Hi 

I'm trying to do something quite simple. I'm trying to change the names of some chromosomes in a vcf file that don't match the reference database that i'm using in snpEff. 

It gives this error. 
```
Traceback (most recent call last):
  File "/Users/lf16/PycharmProjects/scripts/test.py", line 10, in <module>
    rec.chrom = "1"
  File "pysam/libcbcf.pyx", line 3080, in pysam.libcbcf.VariantRecord.chrom.__set__
ValueError: Invalid chromosome/contig
```

I'm sure this is a simple problem but I can't find the answer anywhere. Below is the code. 

```
#!/usr/bin/env python3
from pysam import VariantFile
from pysam import VariantRecord
import sys

bcf_in = VariantFile(sys.argv[1])
vcf_out = VariantFile("out.vcf", 'w', header=bcf_in.header)

for rec in bcf_in.fetch():
    rec.chrom = "1"
    print(rec)

```

Any help is much appreciated. 

Thanks in advance
Lew

**Comment by mattjvincent** [comment]
Not sure if you still need this, but here is something simple...

```
import sys
from pysam import VariantFile
from pysam import VariantHeader

bcf_in = VariantFile(sys.argv[1])

new_header = VariantHeader()

for x in bcf_in.header.records:
    if x.type == "CONTIG":
        new_header.contigs.add(f"chr{x['ID']}", length=x["length"])
    else:
        new_header.add_record(x)
        
for x in bcf_in.header.samples:
    new_header.add_sample(x)

vcf_out = VariantFile("out.vcf", "w", header=new_header) 

for rec in bcf_in.fetch():
    new_rec = vcf_out.new_record()
    new_rec.contig = f"chr{rec.chrom}"
    new_rec.alleles = rec.alleles 
    # copy all the fields you need
    vcf_out.write(new_rec)

vcf_out.close()
bcf_in.close()

```
