### ISSUE TITLE
Is the issue"subprocess-exited-with-error" fixed?

### ISSUE THREAD

**Issue by AlenGhzau** [pysam-developers/pysam#1199]
My system is Win11，while i run the code
`pip install pysam`
meet the error
`Collecting pysam
  Using cached pysam-0.21.0.tar.gz (4.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "D:\Anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Anaconda\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\gah20\AppData\Local\Temp\pip-build-env-4jmtu84i\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\gah20\AppData\Local\Temp\pip-build-env-4jmtu84i\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\gah20\AppData\Local\Temp\pip-build-env-4jmtu84i\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\gah20\AppData\Local\Temp\pip-build-env-4jmtu84i\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 383, in <module>
        File "<string>", line 79, in run_make_print_config
        File "D:\Anaconda\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "D:\Anaconda\lib\subprocess.py", line 505, in run
          with Popen(*popenargs, **kwargs) as process:
        File "D:\Anaconda\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "D:\Anaconda\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by GabrieleSteyer** [comment]
Same issue

**Comment by Completex** [comment]
same issue
