### ISSUE TITLE
ValueError: I/O operation on closed file when reading .vcf file and get samples

### ISSUE THREAD

**Issue by cpwater** [pysam-developers/pysam#1204]
Hi there: 
    I met a problem when reading .vcf file and get samples. Issues as follows:

`Reading GFF file [gff.gff] ... done
Reading VCF file [hapAB_DNA.09005.di.vcf] ... Traceback (most recent call last):
  File "vcf2fasta.py", line 517, in <module>
    main()
  File "vcf2fasta.py", line 84, in main
    samples = [ x for x,y in next(vcf.fetch()).samples.items() ]
  File "pysam/cbcf.pyx", line 2368, in pysam.cbcf.VariantFile.fetch (pysam/cbcf.c:32343)
ValueError: I/O operation on closed file`

I tried to modify this part as but failed.
`    # read variant file and get samples
    print('Reading VCF file [',args.vcf,'] ... ', end='', sep='')
    with pysam.VariantFile(args.vcf) as vcf:
        samples = [ x for x,y in next(vcf.fetch()).samples.items() ]
`
How to solve it? Thx so much!

**Comment by jmarshall** [comment]
I was unable to reproduce any failure using your snippet, Python 3.11, current development pysam, and various VCF files. Please report what Python and pysam versions you're using and how many records are in your VCF file and show us more context of your script.

Your snippet appears to be getting the list of sample names from (usually?) the first VCF record in the file. The sample names are actually recorded on the `#CHROM` header line, so a more direct way to do this would be

```python
with pysam.VariantFile(args.vcf) as vcf:
    samples = list(vcf.header.samples)
```

**Comment by cpwater** [comment]
> I was unable to reproduce any failure using your snippet, Python 3.11, current development pysam, and various VCF files. Please report what Python and pysam versions you're using and how many records are in your VCF file and show us more context of your script.
> 
> Your snippet appears to be getting the list of sample names from (usually?) the first VCF record in the file. The sample names are actually recorded on the `#CHROM` header line, so a more direct way to do this would be
> 
> ```python
> with pysam.VariantFile(args.vcf) as vcf:
>     samples = list(vcf.header.samples)
> ```



Thanks for reply! You remind me version of python. My error occurs in python 3.6 but it worked well in python 3.1. So this might because file control of different version.
