### ISSUE TITLE
AttributeError: module 'array' has no attribute 'typecode'

### ISSUE THREAD

**Issue by weishwu** [pysam-developers/pysam#1233]
I got an error that seems to be related to pysam (version 0.20.0 with python 3.10.9):
```
Traceback (most recent call last):
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 2242, in <module>
    main()
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 2236, in main
    args.func(args)
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 1194, in main_phase
    alignmentwriter(result, outHP22BisSam)
  File "/usr/share/NanoMethPhase/nanomethphase.py", line 411, in alignmentwriter
    out_samRead.set_tags(all_tags)
  File "pysam/libcalignedsegment.pyx", line 2656, in pysam.libcalignedsegment.AlignedSegment.set_tags
  File "pysam/libcalignedsegment.pyx", line 385, in pysam.libcalignedsegment.pack_tags
AttributeError: module 'array' has no attribute 'typecode'
```

One line in my BAM:
```
0a8e9d66-3338-4578-a7ff-fbe08d4e2434	2048	chr1	10001	23	169S15M1D32M1D20M1D11M1D34M1D29M1D30M7I57M1D18M2D5M1D63M12D3M1D13M4D32M1D13M1I18M1I6M1I15M3602S	*	0	0	CCCTAACCCTAACCCTCACCCCTAACCCCTAACCCTAACCCTAACCCTGACCCCTAACCCTAACCCTGACCCTAACCCTAACCCTAACCCTAACCCTCACCCTGACCCTCACCCTGACCCTGACCCTGACCCATAACCCATAACCCTAACCCTAACCCTAACCCTAACCTAACCCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCAACCCTAACCCTAACCCTAACCTAACCCTAACCTAACCCTAACCCTAACCCTAACCTAACCCTAACCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCCGACCCTGACCCTAACCCTAACCCTAACCCTAACCCTGACCCTGACCCTAACCCTAACCCCAACCCCAACCCCAACCCCGGCCCAACCCCAACCCTAACCCTAACCCTAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCCAACCCTAACCCTAAACCCTAACCCTAACCCTAACCCTAACCCCAACCCTAACCCCTAACCCCTAACCCTAACCCTAACCCCTAACCCCTAACCCTAACCCAAATAATCACTCAAAATCATCCTTACACTAAAAATGCTAAACTATACAATTTCTAGAAGAAACAATAGAAGAAAAGCTATGTGCCTTTGGGTTTGGTAATGAATTTTAACAAATGATACAAAAGGTTGACATACACAAAAGAAATGACATTGTGGATTTCTTAATATTTAAAGTTTATACTCTGGAAGACACCTTGTTAAGAGAACAAAAAGACAAGCCACATATTGAAGAAAATATTTGCAAAATACACATCTGAGAAAGAATTTGTCTTCAAAATATATAAAAAAGTATTAAAACTAAACAATAAGTTAAACAGCCCAACTAAAAATGCACACATCTGAACAGACACCTCACCAAAGAAGATCTACAGATGGCAAGTAAAGAAACATCAAAAAGATGCTCAACATACTAGAAAACTGAAAACCACAATGAGATAGCACAGCTGGTCTATATCTCTTAGAACTGCTAAACTCCCTAAAAAATGACAAATTGCTGGAGGAAAAACAAGAACTCTTTTCATTGCCGGTGGAACACAATGTACAAGACCAAAACATGCCACCCCAAAATATAATGGTAGGAAACCAGAATATGCCACCCCAAAATATGTCCCTTTGGCTTAAGAATTATTCCAAGCTGATTATTTTGAAAAAATAAATGCTAACAAAGGAAGTTCTGAAAACAGAGTAGAAGTTACCCTTGTGTAAGGAAAATTTACATCTATAAAGGAAATCCCCATTTAAAAGCTACCTCTCTCTACACCAAGAAGAGAAGGATAACTAAATCACTAAAGAGTCTTTAATAGTGGGATATCTGCCACAACACATTTATACAGATACACAGAATTTTATGGCCAAATGGGTAAATCAAATTCTATTCAAATTAAACAAAATTACTCAGGATGTGGCGTATCCCAGGACAGAATGCATCATGTTGAAAAAGAATTTATGCTACAAATTACTATGGTTTGGATGTGGTTTGTCCCCAAGCCATGTTGAAATTTGACCCCCAATGTGGCAGTGTGGGGCGGTGGGGCCTAGTGGATGGTGTTTGGGTCATGGGGATGGATCCCTCATGAATAGATTAATGTCCTCCATGGGGGTCAGTGGGTACTGCTTCTCATAGGAATGGATTAATTCCTGCAGGAGTAGGTAATTAAAAGAGTCTGGCTTCCTTGGCTTCCCTTTTGCTTTCACTTCTGCTATGTGATCTCTGGTGCACCCCTTGCTCCCCTTCCGCTTTCCACCATGAGGTGAAAAAGACTGAAGCCCCACCAGATGCAACTGCCCAATCTCGGACATTCCAGCTACCAGTATTGTGAGCCAAATGAATCTTTTTCACTTATAAATTACCCAGCCTCAGGTATTCTGTTACAGGAAGCACAAGATGGACTAAGACACAAATGTAGGTAAAAACTCACTGAAGGTGGAGGGAAAATGGTGTTGACCTAAGTCACTTTGAAAATCAATAGAATCTGGAGGCTGAAGGCACATGAACTATACTTCATAATTGGATTACATTTTATAAAGTTATTTCCAACAGAAGCAATTGTGAACAATTGTAAAACCACAGTGTCTGTATCTGGAGTAAAACAATGACTTACATAAGTCGCAGATGGTGGGAACCAGCTTTCTCACTGTTGAAGTGGGAGGTTACAAATTAGCAAGACGAGAAGGCTAGAATGATTCCTGTGATAATAGAGATTGGGAGGATGAAGTCAACGTAAACTTATGCTTAGTTTAATATAGATACACACAGTTCTACATAGAAAACTTTATAATTAGGTGTGTGTAGGTAGGTTAGACACACACATATACTTCCTAGCATTGCTAATGAGGGACAAGATACAATGTGCATTCAGCAGCCAGATGTAAGTTTTCCCACCATTCTGAAAGGAATCAGGCTCTTTGAAGAAATGTCTGATACTAGAACTGGGACAGTATAAATATAGGAGCCAGGATAATCTGGAAGTATCAGAAAGTAAGTACTAAAAAAATTAAAATATATCAAACAAAAATAAAAGCCAATAAAAACAGCTACCGATGGCCAACACAGGAAGGAATTGTGCAACATAATGCTATAGTGTTGAATAATAACTAAAGCTTAAAGTAATTATCTAGGTGTCTGTATTTGTATACCTAGGTGAATAAGCAAATGGAGTTGCATAGAAATCTCCTTTGCAAAAGAATTCCAATAACTGATGTAGACACTCAGGCCATCAAGAAGGTGGAGCCAACTCCTCACTCCGTAAGTGTGGGCTCTGCATAGTGACTTGCTCCAAAAGAACACATGCAGTACGGACAAGGAGGAAAAATAACTTCACAGTGGAGAAATCTGACAAACAGTAGCTCTGCCAAATGATCCAAGTGAACATCAAAGCTGACAGTTCACCTTAGAACATGAAGTGACAATGGGGGACATTCTTTAAAATGCCTGACCAATCCTCCTCAGTGCTATGAAGGTCATCATGAGGTGGAAAGCCTGACACACTGTCACTGCCAGGAAGAGCCTACGTGATGACTACATGTCATGCGGGATCCTGGATGGGATCCTGGGTCAGAGTAAGATAGAACTAAGGGAATCCAAATGAAATATGAACTTTAGTTAATAACAGTCTATCAGTATTGGTTCATTAAGTGTGACAAATTCTGTAAGATAATAATAAGCCATGTGAGACACACTGATTGATAGGAGATGTTAATAACAGAGGAAACTAGGTTGCGGCTACATGGGAAATCTCTGCTTTTTTTTTTTTTTTTTCTGACGATTTCTGTGTAAGTAAAAAGCAGATGTAAAATAAAACTTTATTTAAAACACTTTTTAACACTTCCTTGTTTAATTATTTATACCATGAATTACTAGTAATTGACACTGTTAACTAGTCCTGTTTTTAAAAATAAGAGCATTTATGACACAAAAAATTAAACAGTGCAGACTGATATATAAATCAAAACAAATATTCTTTACACGTTTTCTGTTACAGTAGTAACACATATGTGTAAATTTAAGTATCATATTTTTTTCTTGTGCTATGGTTGTGTCCTAGGTTCATTCTCTAAAATGCTGTTCACCTTAGACCAGGAAAAATATTAACCATACAGACTCTGTTTCCAGTCATAGCTAAATATTTTCAAAAGAGTGACTTTGTAAAAACATGTTCCAATGGCAAATTGATTCATTATGATGGGATCAATTGTACGAGTTCCTGTCTTATTATTTCTTTGCCATGCCTACCTTTTAGCCATAATACAACAGAATCAAATCTGGCCACTGGGAAAAAAAGAAAAAAAAAAGAAAAAAGAAAGGTAGGGTCAGGGAAAAAAAAAGAAAGAATGTGAACAGAACTTATGACCATGATGATTAAATATTTTACCACAATGCTTTCTAAAACAGAAGAGTGTAAAAGGATATTCAAAGTCAATTTCCTCAGCGAGGCTTTGCAGAAAATGAGGAAACTAGAAAAACAAAAATGGCAGGACATTCTATGGGTGATTTTAAATGTTGCTATGTTTTATGGGAAAAAAATACTTTACCTTTTAAAGAATCACAAAGAATTATTGGAAACCCAAACTCTGGAATGTTTCAAATTTAGTTCAGCTTCTATG	''((+8653-8<;?A;5332488<=<=>/-=9:;<:=?A@@<<<<;<<,++++1+;;<=?AD>BAB@11111>@DB?DDEDACECC>AACBD@@??=65555976678;86666778777:98889;/....,***,8;20001;=AF@C@CFA=@ACCD<CDEED:7745;<=B?:;;<@A@;;;78BCEHEICCBFDEBCFSCKA@?A=AAAA>6666<A?8>ACEFHECGEHDDFABD@BEA<===99:?@@ACIBCDCBHDCEA>8:844<>?@BC>>><;@@BCDICB@EEF@BDEEGBDBFGJECFGCSEF@IJECEEE@JIFHJDFA<AD@F@??@=::;;<>10001<>?@BDDLGFFIED@DDCBSICBD=33333455556?ABADFHIA@@A66655;88877;233113-*)()('',.367878?BOSGEGHO8>BDHK@@?A99888?87777=:::99@99888>55545=::999>33323?DDFCEFCDD<9;BEEFEEFEBBACFDEGIGFFB@A@@11111=>B@>>@88555>A:9@@=C<<=:<EEAG@?@>,*6611864=9<>@>B???@;>?>>>?@>>??ACCCBDCB:8778:CDCA@@@AA>>>>>??@?????@??88:111297888977.,,+((/78<AB@@@@AA9++>++BDFHEFDCAA@AB@CDEDFFEDBBCCBAA@?@??EF6320/.--..223?;2223389?@BA?@@@ABBBBB==@??@@?ADDCCD@A?====>ABDFCB33333?9::::D998::<ACMJIFDABBDDCEC@@A?A@9843E>976634112=BDDBBCE?@>??BDIECBABECGEDDBB<<=<;;;99222GIFBA@AAADDCDDABBCCFCAA@@BCEDCA@@@ABA@??@AGEFDKFC<<?EECBCDJSHFHF@?85?FDBFGJHEDFEDEHGFFEFFDFN@?980****)76++++8;<==;764445.---+...=CGGHHMSHKHFBBACCDNEEFEBCDCBDDEFDGGGGEGKED::-)))>FKEEDCEFJGHFFFBCCIHSEFCCDDLDFEFIMEEGG22A@AAADDHEFNIHHEEEESSGD>0000/.-,,-,''(()112226878AGHKGDBD<<GP:8GEFISMJIHIEFDF:54649777789FDFEFEEGFIGSSHLG@=999;@,*,..*'&&'''''((((59>DG99999GA8E98888GFFSKLNIHEGEBB@?7?=@>;;10000244211445??@GGIFSMSSGKLJNKKSJHFHGJKSG@??88999DA?FDGKE;9988:;<7CGHOSHIGIHHEG@89888EGC;730+,<=?FLIIHDFI>=>>CDBAHSSFGFCEELKGLPG222@@???@?;76644;:9.-&&&(%&%%$#$&*))*)+2=BBFGDE==<>GKSMJNSOONDFDFHGCD==6.-++,./211124@BCJMIIMGIMIKGHFFDCCDAA52.--068<778==>@A@DDDDA::;<<SHOS@@?==KLESKJLGHFHLENFSKFSSSKSIEQEAADSCB964-)+'$%%%&9;==FOGJHFHSCGGLGRKKHKLOSSRGIKMGIKNKGKGFMSLF6555656?@?@A@?>@@HJGSSEEIJNOGKIKGGGLNSIFJSKEMGDCCFEIGLF?>::B=<<>=,**)())'''))(((''*--9===AA>?>>>D?>>679980000088=CG@@@?::;<@B64443566;<SJJKPSJKGSGGFHC3KOSHHHNSHLHSSPSSJHGSSSKHSSSSIIJSQSD>A>>>=@@>2A@B@B@AA?AJHIKRSHHHGJJSJSSSNISNFHSJSLSSSKJ?CDIDHHSKPGSI>?>>ASSHIIKSSFFFFJJIJQISSSSFKFGMDCECCLFCCEEISQSMSJISBG89IGOKONSSSIJPHJNHQJLJSF872//--20-'((::<:DCHESHILDHSLD::::AHGSIOJJLISSLHJMHJIQGJHJKSOIGHGKKHHHSISSMJLHIED>@EHACBANM@<=BA8=))((()22201255?CJGHHJHSLJLSNGHSDDCBB42222ESSKSKSKGQISGKSSHISSEKJSKJRSQJSISKIIOHISSSLISJGSMQJEJBAA???===::CCBADCEDDBCBA777778AANGKKHFGDDGISJJSKPHIKLGKJSSKFGSMSSHKOOKIJGDB655555>;;;;GIHSSOQKJISGQIELHGEDHHRJGKLKKNISJSOKSLLSPFSMSJSPSSISF<-,*(()%$$#$')$$$$&&&'',4<>AEKFIEF>GCGB==>?9><=C977788DA:8SSMNIHFJELEEEFGEFMMSISJIFJHKGSJFFQLSISKSLFGSH===<<<B@CSJNLELGGHLDD@?AFHFHGESSGGJFIEEGGSLPKNLQMKSJKMRFSISHQHNKLSSKSPSSHGJIIE;63-7FHONHE2111-DGFSEHKIHSDCFCECORSSSMSSSLJISIISHIGKKSKHIGFDCE7.++,/1899:>DFFDDFSHIJF?@A@BIKJSSLJLMGSMSSJSSSJED889SSSPSSSSLJMRHHFGGSJHSKNSSSGSLISBABAAMSESG>====GECBEBGHBMSNMMAABIEOMGSKOSSLSJSSKKLNHJMLDE0000/1/..//45444459:888777=GEHMGNIGLIEFJKJSSLSSKSNKNSRFSIFJA@AAPCNJDA>===>AESIIEEFJISJEEGSSSJKSFSC>D?CDEHFC????>:--555>?@EB9988<<B>>=4.-,(**489:CEKSGFRSJGJSSKGS@@@FBAFEHSHISSHFB@@ISJSLLOSSLSSNSKSHSSCCGISIJSLSSDDDEMSLSJHHIISNSHSISMKOSMSSSNSKSKSHSSSKSOLSLPOILHSIKLJLGKQPIIJJHKMSIKMSSMGLJPSSGSLHEILIHGSISHNISISFDCEA>('''::KFEGMLSNNNSOJGLEOJEGIGBA(&&&'):DJFSFIFPHEFIGGIISJHMGLSKFHFJPOFOJSSNSSBIEHSHISKSIJLRCECFISFSSHPJSFIS=888==AB?;;<<GFEKLKMIC:4333=>ABBCGSL=:<FSLHSKIESLJKNGH9975:<<<>BC@CHFA<==<???EJFJIFKLKPIIQJKSMJJHSFDFEG888888IFFHKEE=====LIKFSMHHGEGCECHHGHKIMSLSHSHNKSPSMSKJSHSKISSJJISHLGSGIIGIGNSHIMCCDGSSMSHJILSKHNOJPNNSHDCDLSQKSKGCEDEJSNGFFIDECEGFGIHSJSSB??>425;8:?ACECEHBBA7('''';;;;<EJHHLSKSSSHSJSKSIHIHGMED====?ILE?ABB>GEGDIHGH::652CCEDDDFDDFGJIIFLJSLPSMGOH;:,++(&&&(./:;;;;=BQSKHKSSLLMQNKKSJKSHGFESFSGISOHSSLSJIHEHJKORSISJHQILSIGJSSSSSJKLSSSLIH=<<<<=ALEEC<:89:DFSSSJSHMSNJHSKGGSSQFGDFJ<=<<<87889FJJGGPSKSRSEJNISSHIOSLDDHGKS;;;:;?A@BFE>2=@AJGGGELHGKLSOKHSJFJNSINJHGJJGC:99:<GLF9(((((?E;9666@>??SHSKSKNJHDCCEEGGOGMMSISLISHSJSLHSGSJMSJLNJSHOSNSMDDBAEJ><<99;@ACBFDFDISJJOHHMSQSHKHSNSSHKMBAA><===CCFKEREFCCC4444(('&%%%$$$%&&'/21)()()*8'<?8''DIFGSIIGHSNLSH@SSHNIRHLEJGMED31111::98''''(JSGICDDCKGIF=982/.,+33=EGDCBDDAD6/.-+,+)())+,22228?C>D=<<=;AEDMIKSGSLHFSHSPJMGJFIGESSEG?<;8898*)))..../58:9:EMHSHGMILD@??@AC///01////(((-*HGSFJSLMSIHSSGGFGIEKMCDACDCCCDBGFFCGDGFFFEFEGEKIJHECCBCGJFEDEFGSHSJHGFEFHGMGDHGFFGGMGLHHMSNSGHHHPFSFFIHJFSNKIGI@1AACDB?:++++,./<>?D?9KIDFEKECCCED?B=94-++,..<;;66666<;22226:=>?@B((((2;<++++++>==ABB??B	RG:Z:A	MM:Z:C+h?,174,42,186,70,21,45,18,53,9,4,49,36,10,47,3,22,6,27,35,35;C+m?,174,42,186,70,21,45,18,53,9,4,49,36,10,47,3,22,6,27,35,35;	ML:B:C,1,212,4,16,25,3,1,33,1,19,4,3,3,3,19,10,16,2,18,1,254,42,1,239,229,252,0,222,254,1,1,252,1,1,236,244,2,1,237,254	NM:i:49	ms:i:647	AS:i:618	nn:i:0	de:f:0.0649652	tp:A:P	cm:i:20	s1:i:137	s2:i:119	MD:Z:15^C32^T20^C11^C25C8^C29^C33A29A5A17^T5T5T2A3^TA0A0A3^T5T57^CCTAACCCCTAA3^T13^CCCT29T2^C52	rl:i:396
```

My guess is that some tags in my BAM are not compatible with pysam. Any help? Thanks.

**Comment by jmarshall** [comment]
The AttributeError was a pysam bug. Some of the tagged fields being added in `out_samRead.set_tags(all_tags)` must have had invalid value types, and future pysam will report this via a more useful message.
