### ISSUE TITLE
failing to print records when parsing vcf via tabix parser

### ISSUE THREAD

**Issue by misha-at-genestack** [pysam-developers/pysam#130]
```python
Traceback (most recent call last):
  File "./pysamvcftest_vcffile.py", line 12, in <module>
    print record
  File "pysam/TabProxies.pyx", line 350, in pysam.TabProxies.TupleProxy.__str__ (pysam/TabProxies.c:4963)
TypeError: decode() argument 1 must be string, not VCF
```

and

```python
Traceback (most recent call last):
  File "./pysamvcftest_vcffile.py", line 12, in <module>
    print record.info
  File "pysam/cvcf.pyx", line 190, in pysam.cvcf.VCFRecord.info.__get__ (pysam/cvcf.c:4933)
  File "pysam/TabProxies.pyx", line 350, in pysam.TabProxies.TupleProxy.__str__ (pysam/TabProxies.c:4963)
TypeError: decode() argument 1 must be string, not VCF
```

**Comment by AndreasHeger** [comment]
Add unit test to cover this.

**Comment by AndreasHeger** [comment]
Done, see d26cb3818a9488bf5c4755deb07d94a91a35f82e
