### ISSUE TITLE
Python3-related test failures in latest release (0.8.3)

### ISSUE THREAD

**Issue by afif-elghraoui** [pysam-developers/pysam#155]
While packaging the latest release for Debian, I see that there are a good number of failures in the Python3 version of the package. I copied some of them below, but you can see the full test log at http://ci.debian.net/data/packages/unstable/amd64/p/python-pysam/20150806_192500.autopkgtest.log.gz

I imagine you may have fixed some of these already in the current git revision, so is there going to be a new release that passes the test suite?

Please note there are some failures that have to do with renaming the compiled libraries due to Debian's multiarch system; I'm more concerned now with the failures like the ones I list below.

```

======================================================================
ERROR: see issue 62
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.faCiVI/build.j6x/python-pysam-0.8.3+ds1/tests/AlignedSegment_test.py", line 62, in testSettingTagInEmptyRead
    a.tags = (("NM", 1),)
  File "pysam/calignmentfile.pyx", line 3685, in pysam.calignmentfile.AlignedSegment.tags.__set__ (pysam/calignmentfile.c:40029)
  File "pysam/calignmentfile.pyx", line 3525, in pysam.calignmentfile.AlignedSegment.set_tags (pysam/calignmentfile.c:36489)
  File "pysam/calignmentfile.pyx", line 2359, in pysam.calignmentfile._pack_tags (pysam/calignmentfile.c:26080)
KeyError: b'C'

======================================================================
ERROR: testAddTags (AlignedSegment_test.TestTags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.faCiVI/build.j6x/python-pysam-0.8.3+ds1/tests/AlignedSegment_test.py", line 401, in testAddTags
    ('PG', 'P1'), ('XT', 'U')]
  File "pysam/calignmentfile.pyx", line 3685, in pysam.calignmentfile.AlignedSegment.tags.__set__ (pysam/calignmentfile.c:40029)
  File "pysam/calignmentfile.pyx", line 3525, in pysam.calignmentfile.AlignedSegment.set_tags (pysam/calignmentfile.c:36489)
  File "pysam/calignmentfile.pyx", line 2359, in pysam.calignmentfile._pack_tags (pysam/calignmentfile.c:26080)
KeyError: b'C'

======================================================================
ERROR: test for tag parsing
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.faCiVI/build.j6x/python-pysam-0.8.3+ds1/tests/AlignedSegment_test.py", line 442, in testTagParsing
    entry.set_tags(before)
  File "pysam/calignmentfile.pyx", line 3525, in pysam.calignmentfile.AlignedSegment.set_tags (pysam/calignmentfile.c:36489)
  File "pysam/calignmentfile.pyx", line 2359, in pysam.calignmentfile._pack_tags (pysam/calignmentfile.c:26080)
KeyError: b'C'

======================================================================
ERROR: testTagsUpdatingFloat (AlignedSegment_test.TestTags)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/adt-run.faCiVI/build.j6x/python-pysam-0.8.3+ds1/tests/AlignedSegment_test.py", line 388, in testTagsUpdatingFloat
    ('PG', 'P1'), ('XT', 'U')]
  File "pysam/calignmentfile.pyx", line 3685, in pysam.calignmentfile.AlignedSegment.tags.__set__ (pysam/calignmentfile.c:40029)
  File "pysam/calignmentfile.pyx", line 3525, in pysam.calignmentfile.AlignedSegment.set_tags (pysam/calignmentfile.c:36489)
  File "pysam/calignmentfile.pyx", line 2359, in pysam.calignmentfile._pack_tags (pysam/calignmentfile.c:26080)
KeyError: b'C'
```

Thank you

**Comment by AndreasHeger** [comment]
Thanks, I will take a look. I was waiting for a new htslib release, but I can make an additional release earlier. Will be on leave but can do this early Sep.

**Comment by afif-elghraoui** [comment]
On الأربعاء 12 آب 2015 08:07, Andreas Heger wrote:
>
> Thanks, I will take a look. I was waiting for a new htslib release,
> but I can make an additional release earlier. Will be on leave but can
> do this early Sep.
>
>

Thanks for getting back to me. I think waiting for the next htslib
release will be fine. Don't worry about rushing this now.
