### ISSUE TITLE
Access of TabixFile remote header produces IOError

### ISSUE THREAD

**Issue by dcolligan** [pysam-developers/pysam#157]
When getting a remote compressed vcf file via `TabixFile`, accessing the header attribute produces an `IOError`, even though fetches work fine:
```
>>> import pysam
>>> url = 'ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz'
>>> tab = pysam.TabixFile(url)
>>> tab.header
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/ctabix.pyx", line 449, in pysam.ctabix.TabixFile.header.__get__ (pysam/ctabix.c:5163)
  File "pysam/ctabix.pyx", line 604, in pysam.ctabix.GZIterator.__init__ (pysam/ctabix.c:6729)
IOError: No such file or directory: ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/release/20130502/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
>>> tab.contigs[0]
'1'
>>> contig = tab.contigs[0]
>>> tab.fetch(contig).next()
'1\t10177\trs367896724\tA\tAC...
```
Is this expected behavior?  If it is, would it be possible to just not have the header attribute set when it would cause an `IOError`?

**Comment by AndreasHeger** [comment]
Thanks for submitting this, it is indeed not the intended behaviour. I will fix this.
