### ISSUE TITLE
How to use pysam on python 2.7

### ISSUE THREAD

**Issue by csuliweilong** [pysam-developers/pysam#177]
Hi,

The python version of my server is 2.7.3.

When instaling pysam, I got an error:

Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    import hashlib
  File "/usr/local/lib/python2.6/hashlib.py", line 138, in <module>
    sha224 = __get_builtin_constructor('sha224')
  File "/usr/local/lib/python2.6/hashlib.py", line 66, in __get_builtin_constructor
    import _sha256
ImportError: No module named _sha256

It seemd that pysam is unable to be installed on python 2.7.

How to solve this problem?

**Comment by AndreasHeger** [comment]
You seem to be using python 2.6?

**Comment by AndreasHeger** [comment]
Closing this for now, please reopen if it persists.
