### ISSUE TITLE
Error loading empty VCFs

### ISSUE THREAD

**Issue by brendanofallon** [pysam-developers/pysam#259]
Looks like there's an issue when attempting to create a VariantFile for a VCF with no records:

    >>> import pysam
    >>> print pysam.__version__
    0.9.0
    >>> v = pysam.VariantFile("empty.vcf.gz")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pysam/cbcf.pyx", line 3273, in pysam.cbcf.VariantFile.__init__ (pysam/cbcf.c:48009)
      File "pysam/cbcf.pyx", line 3524, in pysam.cbcf.VariantFile.open (pysam/cbcf.c:51665)
      File "pysam/cbcf.pyx", line 3022, in pysam.cbcf.makeTabixIndex (pysam/cbcf.c:45377)
      File "pysam/cbcf.pyx", line 3002, in pysam.cbcf.TabixIndex.__init__ (pysam/cbcf.c:44918)
    ValueError: Cannot retrieve reference sequence names

'empty.vcf.gz' contains a valid header, etc., but no records. That should be OK, right?

**Comment by Arkanosis** [comment]
Hi,

Same issue there. I don't think there should be any error when loading an empty but otherwise valid VCF file, let alone a generic error like `ValueError` you can't `except` without risking of catching totally unrelated (real) errors at the same time.

Best regards

**Comment by bioinformed** [comment]
@Arkanosis: Thanks for the problem report.  I though I'd fixed this bug, but obviously not.  I see what is happening and will have a fix shortly.

**Comment by Arkanosis** [comment]
Hi @bioinformed : thanks for the very quick reply! Just to be sure I'm not reporting something that has been fixed in the past, I've installed pysam using `pip3 install pysam` yesterday. That is, I'm running pysam 0.9.1.4, built on samtools and htslib 1.3.1.

Let me know if I can be of any help.

Thanks again!

**Comment by Arkanosis** [comment]
So I tried with the new 0.10.0 release and this time, I get a native crash in htslib:

```
Program received signal SIGSEGV, Segmentation fault.
bcf_hdr_fmt_text (hdr=0x846980, is_bcf=0, len=0x7fffffffce70) at htslib/vcf.c:1419
1419    htslib/vcf.c: No such file or directory.
        in htslib/vcf.c
(gdb) bt
#0  bcf_hdr_fmt_text (hdr=0x846980, is_bcf=0, len=0x7fffffffce70) at htslib/vcf.c:1419
#1  0x00002aaab211b8fa in vcf_hdr_write (fp=0xb63ef0, h=Unhandled dwarf expression opcode 0xf3
) at htslib/vcf.c:1450
#2  0x00002aaab211ba7b in bcf_hdr_write (hfp=0xb63ef0, h=0x846980) at htslib/vcf.c:870
#3  0x00002aaab68cfd6f in __pyx_pf_5pysam_7libcbcf_11VariantFile_4close (
    __pyx_v_self=0x2aaab6b6de18, unused=Unhandled dwarf expression opcode 0xf3
) at pysam/libcbcf.c:51545
#4  __pyx_pw_5pysam_7libcbcf_11VariantFile_5close (__pyx_v_self=0x2aaab6b6de18, unused=Unhandled dwarf expression opcode 0xf3
)
    at pysam/libcbcf.c:51440
#5  0x00002aaab20e7378 in __Pyx_PyObject_CallMethO (__pyx_v_self=Unhandled dwarf expression opcode 0xf3
) at pysam/libchtslib.c:8237
#6  __Pyx_PyObject_CallNoArg (__pyx_v_self=Unhandled dwarf expression opcode 0xf3
) at pysam/libchtslib.c:8306
#7  __pyx_pf_5pysam_10libchtslib_7HTSFile_6__exit__ (__pyx_v_self=Unhandled dwarf expression opcode 0xf3
) at pysam/libchtslib.c:2921
#8  __pyx_pw_5pysam_10libchtslib_7HTSFile_7__exit__ (__pyx_v_self=Unhandled dwarf expression opcode 0xf3
) at pysam/libchtslib.c:2881
#9  0x00000000005827b9 in PyCFunction_Call (func=0x2aaab6b67d80, args=0x2aaab6b6e558, 
    kwds=<value optimized out>) at Objects/methodobject.c:98
#10 0x000000000043338f in PyObject_Call (callable=0x2aaab6b67d80) at Objects/abstract.c:2165
#11 PyObject_CallFunctionObjArgs (callable=0x2aaab6b67d80) at Objects/abstract.c:2445
#12 0x00000000004e3cd5 in PyEval_EvalFrameEx (f=<value optimized out>, 
    throwflag=<value optimized out>) at Python/ceval.c:3192
#13 0x00000000004e9a33 in fast_function (f=<value optimized out>, 
    throwflag=<value optimized out>) at Python/ceval.c:4803
#14 call_function (f=<value optimized out>, throwflag=<value optimized out>)
    at Python/ceval.c:4730
#15 PyEval_EvalFrameEx (f=<value optimized out>, throwflag=<value optimized out>)
    at Python/ceval.c:3236
#16 0x00000000004eb35a in _PyEval_EvalCodeWithName (_co=<value optimized out>, 
    globals=<value optimized out>, locals=<value optimized out>, args=<value optimized out>, 
    argcount=0, kws=0x0, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, 
    qualname=0x0) at Python/ceval.c:4018
#17 0x00000000004eb52d in PyEval_EvalCodeEx (co=<value optimized out>, 
    globals=<value optimized out>, locals=<value optimized out>) at Python/ceval.c:4039
#18 PyEval_EvalCode (co=<value optimized out>, globals=<value optimized out>, 
    locals=<value optimized out>) at Python/ceval.c:777
#19 0x0000000000510a81 in run_mod (mod=<value optimized out>, filename=<value optimized out>, 
    globals=0x2aaab1a5d488, locals=0x2aaab1a5d488, flags=<value optimized out>, 
    arena=<value optimized out>) at Python/pythonrun.c:976
#20 0x00000000005127c5 in PyRun_FileExFlags (fp=0x917f60, filename_str=<value optimized out>, 
    start=<value optimized out>, globals=0x2aaab1a5d488, locals=0x2aaab1a5d488, closeit=1, 
    flags=0x7fffffffd690) at Python/pythonrun.c:929
#21 0x00000000005129a7 in PyRun_SimpleFileExFlags (fp=0x917f60, filename=<value optimized out>, 
    closeit=1, flags=0x7fffffffd690) at Python/pythonrun.c:396
#22 0x000000000041f333 in run_file (argc=<value optimized out>, argv=<value optimized out>)
    at Modules/main.c:318
#23 Py_Main (argc=<value optimized out>, argv=<value optimized out>) at Modules/main.c:768
#24 0x000000000041b725 in main (argc=5, argv=0x7fffffffd808) at ./Programs/python.c:65
```

(Still trying to parse a VCF with a valid header but no variant. VCF files with variants work like a charm.)

Thanks again!
