### ISSUE TITLE
pysam.sort error

### ISSUE THREAD

**Issue by ycl6** [pysam-developers/pysam#291]
pysam: 0.9.0
samtools: 1.3.1
htslib: 1.3.1

I think this is because ```samtools sort``` now uses a new output param. Is there a fix to perform sorting with pysam?

```
>>> import pysam
>>> pysam.sort("reads.bam","reads.sorted")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python2.7/site-packages/pysam-0.9.0-py2.7-linux-x86_64.egg/pysam/utils.py", line 72, in __call__
    "\n".join(stderr)))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\n\nUsage: samtools sort [options...] [in.bam]\n\nOptions:\n\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n\n  -n         Sort by read name\n\n  -o FILE    Write final output to FILE rather than standard output\n\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n\n  -@, --threads INT\n\n             Set number of sorting and compression threads [1]\n\n      --input-fmt-option OPT[=VAL]\n\n               Specify a single input file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n\n               Specify output format (SAM, BAM, CRAM)\n\n      --output-fmt-option OPT[=VAL]\n\n               Specify a single output file format option in the form\n\n               of OPTION or OPTION=VALUE\n\n      --reference FILE\n\n               Reference sequence FASTA FILE [null]\n'
>>>
```

**Comment by ycl6** [comment]
OK, I found the command that will work:

```
pysam.sort("-o", "reads.sorted.bam", "reads.bam")
```

**Comment by AndreasHeger** [comment]
Thanks for providing the solution, closing this issue.
