### ISSUE TITLE
Problem installing through pip

### ISSUE THREAD

**Issue by MortazaG** [pysam-developers/pysam#403]
Hi, I'm trying to install pysam through pip on a windows 10 computer with Anaconda2 (Python 2.7), but I get the following error:

```
Collecting pysam
  Using cached pysam-0.10.0.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\**\appdata\local\temp\pip-build-aqeu1n\pysam\setup.py", l
ine 210, in <module>
        htslib_make_options = run_make_print_config()
      File "c:\users\**\appdata\local\temp\pip-build-aqeu1n\pysam\setup.py", l
ine 63, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Anaconda2\lib\subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "C:\Anaconda2\lib\subprocess.py", line 390, in __init__
        errread, errwrite)
      File "C:\Anaconda2\lib\subprocess.py", line 640, in _execute_child
        startupinfo)
    WindowsError: [Error 2] Can't find the file

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\**\app
data\local\temp\pip-build-aqeu1n\pysam\
```

Any help?

**Comment by Sahilshetye** [comment]
#353  This is due to using Windows  instead of linux.  Refer this issue for possible solution

**Comment by AndreasHeger** [comment]
merged with #575

**Comment by loveanao** [comment]
(pythonProject) PS G:\ProjectPy\pythonProject\pysam> pip install pysam
Collecting pysam
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "G:\ProjectPy\pythonProject\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "G:\ProjectPy\pythonProject\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "G:\ProjectPy\pythonProject\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel       
          return hook(config_settings)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-g2z2cy06\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_w
heel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-g2z2cy06\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires     
          self.run_setup()
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-g2z2cy06\overlay\Lib\site-packages\setuptools\build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ZrSpring\AppData\Local\Temp\pip-build-env-g2z2cy06\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\dev\python\3.10.14\lib\subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\dev\python\3.10.14\lib\subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\dev\python\3.10.14\lib\subprocess.py", line 1456, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1


OS: WIN10 22H2
python: 3.10.14

**Comment by ZCasual** [comment]
pytorch) K:\>pip install pysam
Collecting pysam
  Downloading pysam-0.22.1.tar.gz (4.6 MB)
     ---------------------------------------- 4.6/4.6 MB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      '.' 不是内部或外部命令，也不是可运行的程序
      或批处理文件。
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "E:\soft\aconda\envs\pytorch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "E:\soft\aconda\envs\pytorch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "E:\soft\aconda\envs\pytorch\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Z_Casual\AppData\Local\Temp\pip-build-env-b6aiwjq5\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\Z_Casual\AppData\Local\Temp\pip-build-env-b6aiwjq5\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\Z_Casual\AppData\Local\Temp\pip-build-env-b6aiwjq5\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\Z_Casual\AppData\Local\Temp\pip-build-env-b6aiwjq5\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "E:\soft\aconda\envs\pytorch\lib\subprocess.py", line 420, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "E:\soft\aconda\envs\pytorch\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "E:\soft\aconda\envs\pytorch\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "E:\soft\aconda\envs\pytorch\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
