### ISSUE TITLE
pysam installs but won't import

### ISSUE THREAD

**Issue by christakahashi** [pysam-developers/pysam#464]
pysam doesn't seem to be installing correctly for me.  pip finishes successfully but I get a ValueError when i import pysam.

```
[xx ~]$ pip install pysam
Collecting pysam
  Using cached pysam-0.11.2.tar.gz
Installing collected packages: pysam
  Running setup.py install for pysam ... done
Successfully installed pysam-0.11.2


[xx ~]$ python
Python 2.7.11 (default, Jun  2 2016, 16:21:40)
[GCC Intel(R) C++ gcc 4.8 mode] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/my/home/dir/.local/intel/intelpython27/lib/python2.7/site-packages/pysam/__init__.py", line 20, in <module>
    import pysam.libcvcf as libcvcf
  File "pysam/libctabixproxies.pxd", line 28, in init pysam.libcvcf (pysam/libcvcf.c:32677)
ValueError: pysam.libctabixproxies.GTFProxy has the wrong size, try recompiling. Expected 80, got 88
```

**Comment by bioinformed** [comment]
Thanks for the report.  We are aware of the problem and will have a fix out soon.  See #453 for the latest updates.

**Comment by christakahashi** [comment]
Ah.  Thanks for the info!  I was able to get pip to install 0.11.1 and that seems to work.

**Comment by bioinformed** [comment]
pysam 0.11.2.1 has been released with a fix for this bug.

**Comment by christakahashi** [comment]
Great!  Can confirm 0.11.2.1 works for me.
