### ISSUE TITLE
Errors while reading cram + index when there are only headers

### ISSUE THREAD

**Issue by jmtcsngr** [pysam-developers/pysam#483]
While using pysam@0.1.2 @jeromekelleher and I identified a problem when opening a cram file + index with only headers. The issue can also be replicated with pysam@0.11.2.2

```bash
$ samtools --version
samtools 1.4
Using htslib 1.4
Copyright (C) 2017 Genome Research Ltd.

$ pip freeze
htsget==0.1.2
humanize==0.5.1
pysam==0.11.2.2
requests==2.13.0
six==1.10.0
wheel==0.24.0
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ samtools index original.cram
$ samtools view -O CRAM original.cram 'chr1:138532877-139175172' > empty_region.cram
$ samtools view empty_region.cram
$ samtools index empty_region.cram

$ python
Python 2.7.10 (default, Sep  3 2015, 11:05:41) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> f = pysam.AlignmentFile("original.cram")
>>> g = pysam.AlignmentFile("empty_region.cram")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/libcalignmentfile.pyx", line 401, in pysam.libcalignmentfile.AlignmentFile.__cinit__ (pysam/libcalignmentfile.c:5835)
  File "pysam/libcalignmentfile.pyx", line 672, in pysam.libcalignmentfile.AlignmentFile._open (pysam/libcalignmentfile.c:9325)
IOError: error while opening index for 'empty_region.cram'
```
[original.cram.zip](https://github.com/pysam-developers/pysam/files/1074409/original.cram.zip)

**Comment by AndreasHeger** [comment]
Thanks for the test case, will look into this.

**Comment by AndreasHeger** [comment]
Hi, when giving without a region, samtools view does not open the index. But see for example:
```
samtools view empty_region.cram chr1
[main_samview] random alignment retrieval only works for indexed BAM or CRAM files.
```
Unfortunately, by default pysam notices that the index exists and opens it. To work around this in pysam:
```
>>> import pysam
>>> g = pysam.AlignmentFile("empty_region.cram", filepath_index="noindex.cram")
__main__:1: UserWarning: unable to open index at b'empty_region.cram'
>>> g.fetch(until_eof=True)
<pysam.libcalignmentfile.IteratorRowAll object at 0x2b1c9120dee8>
>>> 
```
This looks to me like an htslib issue and I will raise it there.

**Comment by AndreasHeger** [comment]
Issue has been fixed in htslib.
