### ISSUE TITLE
NotImplementedError: seek not implemented in files compressed by method 1

### ISSUE THREAD

**Issue by unfashionable** [pysam-developers/pysam#536]
I have this error when reading multiple vcf.gz files in docker image.

This is part of the code:

```
def fill_feature_mat(rows):
	snps_featurs=pd.DataFrame(np.zeros([len(rows),len(my_snp_list)]),index=rows,columns=my_snp_list)
	for index in rows:
		vcf_file=validation_data.loc[index,'WES_mutationFileMutect']
		if pd.isnull(vcf_file):
			continue
		vcf_file = vcf_dir + vcf_file
		f=pysam.VariantFile(vcf_file)
		for rec in f.fetch():
			if (rec.id != None):
				if (rec.id in my_snp_list):
					snps_featurs.set_value(index,rec.id,1)
	return snps_featurs
pool = Pool(ncpus)  
snps_featurs = pd.concat(pool.map(fill_feature_mat,sub_tasks))
pool.close()
pool.join()
```
The error is: 

```
Traceback (most recent call last):
  File "./prepare_data_matrix.py", line 160, in <module>
    indel_variant_stat = pd.concat(pool.map(fill_caleb_features,sub_tasks))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
NotImplementedError: seek not implemented in files compressed by method 1
```

I don't have this error when I run it in my machine. Not sure why it can be run in docker. 

Thank you!
Yichao

**Comment by robertampower** [comment]
Hi, did you ever resolve this issue? I"m having a similar problem...

Thanks!

Rob

**Comment by unfashionable** [comment]
Yes. I did.

Just use an older version of pysam. I can't remember which version worked.

**Comment by robertampower** [comment]
Cheers! I realised my issue was actually due to the way the VCF file was compressed (needed to be bgzip)

**Comment by amirkdv** [comment]
For anyone else ending up here, and to elaborate on @robertampower's answer: pysam (at least as of 0.16.1) can only open GZ files that follow the BGZF ([spec](https://samtools.github.io/hts-specs/SAMv1.pdf), see section 4) are created by [bgzip](http://www.htslib.org/doc/bgzip.html), and not normal gzip.

To reproduce:
```
$ gzip -c test.vcf > test.vcf.gz
$ python -c 'import pysam; pysam.VariantFile("test.vcf")'     # works
$ python -c 'import pysam; pysam.VariantFile("test.vcf.gz")'  # crashes
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pysam/libcbcf.pyx", line 4036, in
  pysam.libcbcf.VariantFile.__init__
  File "pysam/libcbcf.pyx", line 4299, in pysam.libcbcf.VariantFile.open
  File "pysam/libchtslib.pyx", line 516, in
  pysam.libchtslib.HTSFile.tell
  NotImplementedError: seek not implemented in files compressed by method 1
```

Resolution (on Debian/Ubuntu):
``` 
$ sudo apt-get install tabix
$ bgzip -c test.vcf > test_bgzip.vcf.gz
$ python -c 'import pysam; pysam.VariantFile("test_bgzip.vcf.gz")' # works
```
