### ISSUE TITLE
pileup: TypeError: Cannot convert FastaFile to Fastafile

### ISSUE THREAD

**Issue by bredeson** [pysam-developers/pysam#543]
Dear pysam devs,

Thank you for writing and maintaining this extremely useful and productivity-boosting code! It makes my life so much easier :-)

I'm using Anaconda 4.3.0 Python (2.7.13) with pysam 0.12.0.1 and am encountering an issue trying to pass `pileup()` a fasta file via its `fastafile` kwarg. Your guidance would be appreciated:

```
Traceback (most recent call last):
  File "./medianDepth.py", line 42, in <module>
    main(sys.argv[1:])
  File "./medianDepth.py", line 22, in main
    for pile in bam.pileup(contig, fastafile=fasta, stepper='nofilter'):
  File "pysam/libcalignmentfile.pyx", line 997, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libcalignmentfile.pyx", line 2120, in pysam.libcalignmentfile.IteratorColumn.__cinit__
TypeError: Cannot convert pysam.libcfaidx.FastaFile to pysam.libcfaidx.Fastafile
```

**Comment by AndreasHeger** [comment]
Thanks! This was due to derived Fastafile (deprecated, for backwards compatability) being specified as argument to pileup instead of FastaFile. It should now work with both.
