### ISSUE TITLE
error on attempt to do anything with pysamstats...install error?

### ISSUE THREAD

**Issue by scottaroony** [pysam-developers/pysam#559]
I'm sure I'm doing something wrong (ie. noob) but here's the error I get after installing pysam and pysamstats:

$ pysamstats 
Traceback (most recent call last):
  File "/usr/local/bin/pysamstats", line 10, in <module>
    import pysamstats
  File "/usr/local/lib/python2.7/dist-packages/pysamstats/__init__.py", line 8, in <module>
    from .pileup import *
  File "/usr/local/lib/python2.7/dist-packages/pysamstats/pileup.py", line 6, in <module>
    import pysamstats.opt as opt
  File "libcfaidx.pxd", line 51, in init pysamstats.opt (pysamstats/opt.c:34893)
AttributeError: 'module' object has no attribute 'PersistentFastqProxy'

Any help appreciated.

**Comment by scottaroony** [comment]
sorry, bouncing around the forums...reposted in pysamstats forum.
