### ISSUE TITLE
"an integer is required" error when calling count_coverage()

### ISSUE THREAD

**Issue by terrycojones** [pysam-developers/pysam#610]
I'm using `pysam` 0.13 under Python 3.5.0 on OS X 10.13.2.  Running this:

```python
import sys
from pysam import AlignmentFile

af = AlignmentFile(sys.stdin)
af.count_coverage()
```
with a BAM file (sorted and indexed) on `stdin` (or when instantiating `AlignmentFile` with a `str` filename argument) produces the following:
```
Traceback (most recent call last):
  File "./fred.py", line 5, in <module>
    af.count_coverage()
  File "pysam/libcalignmentfile.pyx", line 1185, in pysam.libcalignmentfile.AlignmentFile.count_coverage (pysam/libcalignmentfile.c:13065)
TypeError: an integer is required
```

**Comment by AndreasHeger** [comment]
Thanks. You will need give the call at least a chromosome. I have added a test.
The error message is misleading, not sure why. On my system (linux, py36) I get:

```TypeError: count_coverage() takes at least 1 positional argument (0 given)
```
I have added a test.
