### ISSUE TITLE
AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'

### ISSUE THREAD

**Issue by Pezhvuk** [pysam-developers/pysam#614]
Hi,
I have updated my pysam, but, I'm still receiving the following error when I
 run a script that uses cigarstring. The following is the key error:

`AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'`

And here is the whole output:

`parameter dir '_output/_home_pejvak_partis_test_example' does not exist, so caching a new set of parameters before running action 'annotate'
caching parameters
vsearch: 250 / 250 v annotations (0 failed) in 0.1 sec
    keeping 20 / 239 v genes
smith-waterman 
         step  seqs    procs     ig-sw time    processing time
           1    250      1  Traceback (most recent call last):
  File "./bin/partis", line 627, in <module>
    args.func(args)
  File "./bin/partis", line 189, in run_partitiondriver
    parter.cache_parameters()
  File "/home/pejvak/partis/python/partitiondriver.py", line 260, in cache_parameters
    self.find_new_alleles()
  File "/home/pejvak/partis/python/partitiondriver.py", line 189, in find_new_alleles
    self.run_waterer()
  File "/home/pejvak/partis/python/partitiondriver.py", line 170, in run_waterer
    waterer.run(cachefname if write_cachefile else None)
  File "/home/pejvak/partis/python/waterer.py", line 89, in run
    self.read_output(base_outfname, n_procs)
  File "/home/pejvak/partis/python/waterer.py", line 377, in read_output
    qinfo = self.read_query(sam.references, readlist)
  File "/home/pejvak/partis/python/waterer.py", line 521, in read_query
    if 'I' in read.cigarstring or 'D' in read.cigarstring:  # shm indels!
AttributeError: 'csamtools.AlignedRead' object has no attribute 'cigarstring'
       1.5     
Traceback (most recent call last):
  File "./bin/partis", line 627, in <module>
    args.func(args)
  File "./bin/partis", line 202, in run_partitiondriver
    check_call(newargv)
  File "/home/pejvak/anaconda3/envs/partis/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['./bin/partis', 'cache-parameters', '--infname', '/home/pejvak/partis/test/example.fa']' returned non-zero exit status 1`

I would appreciate any help with this.
Cheers,
Pej.

**Comment by AndreasHeger** [comment]
Thanks, which version of pysam are you using?

**Comment by AndreasHeger** [comment]
Closing this issue for now, likely to be pysam version issue.
