### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by beyhangl** [pysam-developers/pysam#624]
Using cached pysam-0.14.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\asus\appdata\local\temp\pip-build-lj2v9v\pysam\setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "c:\users\asus\appdata\local\temp\pip-build-lj2v9v\pysam\setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Users\asus\Anacondam\envs\bioinformatics\lib\subprocess.py", line 212, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "C:\Users\asus\Anacondam\envs\bioinformatics\lib\subprocess.py", line 390, in __init__
        errread, errwrite)
      File "C:\Users\asus\Anacondam\envs\bioinformatics\lib\subprocess.py", line 640, in _execute_child
        startupinfo)
    WindowsError: [Error 2] Sistem belirtilen dosyayi bulamiyor

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\asus\appdata\local\temp\pip-build-lj2v9v\pysam\

**Comment by alizrrao** [comment]
I get the same error when trying to install pysam, the last line in English is:
