### ISSUE TITLE
Impossible to assign None to vector values in a VCF

### ISSUE THREAD

**Issue by TMiguelT** [pysam-developers/pysam#632]
The VCF 4.2 spec states:
> If any of the fields is missing, it is replaced with the missing value. For example if the FORMAT is `GT:GQ:DP:HQ` then `0 | 0 : . : 23 : 23, 34` indicates that GQ is missing.

Which suggests that any field can be set to a placeholder (`.`), even vector fields.

However, if you try to assign a multi-value field to None (which corresponds to the `.` character), like this:
```python
import pysam
vcf = pysam.VariantFile('TCRBOA2.vardict.vcf.gz')
for rec in vcf.fetch():
    rec.samples['TUMOR']['AD'] = None
```

You get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "pysam/libcbcf.pyx", line 3442, in pysam.libcbcf.VariantRecordSample.__setitem__
  File "pysam/libcbcf.pyx", line 855, in pysam.libcbcf.bcf_format_set_value
  File "pysam/libcbcf.pyx", line 579, in pysam.libcbcf.bcf_check_values
TypeError: values expected to be 2-tuple, given len=1
```

**Comment by bioinformed** [comment]
Since GT is diploid, the error is telling to to assign `(None, None)`.  Allowing a scalar `None` to set the field to missing regardless of cardinality is probably not a bad idea

**Comment by TMiguelT** [comment]
It is telling me to assign a tuple, yes, but if I do this, the resulting FMT field will have a value of `.,.`, which is slightly different and more confusing than simply `.`. I think all FMT fields should allow assignment to `None` in this way.
