### ISSUE TITLE
Pileup broken in version 0.14

### ISSUE THREAD

**Issue by bsipos** [pysam-developers/pysam#634]
Hello,

Pileup seems to be broken in version 0.14 under Python 3.6.2:

```
#!/usr/bin/env python

import pysam

print(pysam.__version__)
bamfile = pysam.AlignmentFile('stat_test.bam', 'rb')

for pc in bamfile.pileup():
    print(pc.reference_name)
```
The above script returns:

```
0.14
Traceback (most recent call last):
  File "./test.py", line 9, in <module>
    print(pc.reference_name)
  File "pysam/libcalignedsegment.pyx", line 2807, in pysam.libcalignedsegment.PileupColumn.reference_name.__get__
AttributeError: 'pysam.libcalignedsegment.PileupColumn' object has no attribute '_alignment_file'
```

Cheers,
Botond

**Comment by AndreasHeger** [comment]
Thanks, fixed this this in: 
https://github.com/pysam-developers/pysam/commit/6b345a3889b5941ead22930ae80ffadc881321f4
Will make a bugfix release shortly.
