### ISSUE TITLE
Unable to install pysam on AWS Ubuntu

### ISSUE THREAD

**Issue by harshameghadri** [pysam-developers/pysam#637]
Could you just guide me? I had used the following commands and I get the same error.

pip install pysam

Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

pip3 install pysam

Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by AndreasHeger** [comment]
This looks like a pip issue?

**Comment by harshameghadri** [comment]
I overcame using conda. I think it was a pip problem.
