### ISSUE TITLE
pileupcolumn.pileups is broken in pysam 0.8.0 and 0.8.1

### ISSUE THREAD

**Issue by StuntsPT** [pysam-developers/pysam#64]
Here is a quick script to test it:

```python
#!/usr/bin/python3

import pysam


def BAMtest(bamfile_name):

    # Set bamfile 'settings'
    bamfile = pysam.Samfile(bamfile_name, 'rb')

    for refs in bamfile.references:
        print(refs)
        for pileupcolumn in bamfile.pileup(refs):
            for pileupread in pileupcolumn.pileups:
                print(pileupread)
                print(str(pileupread))


def RunModule(bamfile_name):
    """Run the module."""
    BAMtest(bamfile_name)

if __name__ == "__main__":
    from sys import argv
    RunModule(argv[1])
```

This script errors out with:

```bash
python3 ~/aa.py Taes.bam
Taes_c1
Traceback (most recent call last):
  File "/home/francisco/aa.py", line 25, in <module>
    RunModule(argv[1])
  File "/home/francisco/aa.py", line 21, in RunModule
    BAMtest(bamfile_name)
  File "/home/francisco/aa.py", line 15, in BAMtest
    print(pileupread)
  File "calignmentfile.pyx", line 3495, in pysam.calignmentfile.PileupRead.__str__ (pysam/calignmentfile.c:37217)
  File "calignmentfile.pyx", line 3527, in pysam.calignmentfile.PileupRead.is_refskip.__get__ (pysam/calignmentfile.c:37807)
AttributeError: 'pysam.calignmentfile.PileupRead' object has no attribute '_is_refskip'
```

It throws no errors with pysam 0.7.8.
Tested on python 2.7, 3.2 and 3.4

**Comment by StuntsPT** [comment]
Seems to be solves with commit 9400112034479bad7a217fbe5b920cbad90db2d .
It was actually a duplicate of #61 .
Closing.
