### ISSUE TITLE
Implementing editable VCF headers

### ISSUE THREAD

**Issue by TMiguelT** [pysam-developers/pysam#668]
At the moment, VCF headers are read-only in `pysam`. I currently need to be able to rename VCF headers, so have been working on implementing this feature. An overview of my fork can be found here: https://github.com/pysam-developers/pysam/compare/master...TMiguelT:master

I have a few quick questions:
- Does my implementation make sense? 
- Is there any serious issue with editing the headers that I'm missing? e.g. will it break some kind of pointer in the variant records?
- Why does setting the ID of a `VariantHeaderRecord` not work, even though setting all the other fields does work? e.g. 
    ```python
    import pysam
    v = pysam.VariantFile("some_vcf.vcf")
    v.header.info["AF"].name = "IAF"
    ```
    Which fails with:
    ``` 
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "pysam/libcbcf.pyx", line 1489, in pysam.libcbcf.VariantMetadata.name.__set__
      File "pysam/libcbcf.pyx", line 1307, in pysam.libcbcf.VariantHeaderRecord.__setitem__
    KeyError: 'cannot find metadata key'
    ```

**Comment by bioinformed** [comment]
Thanks for looking into this important missing functionality.  It is an area that I've been tried to make progress on, but the underlying C APIs are so fragile, create dangling references, and allow interpreter crashes.  I'll definitely take a look at your work and help with the debugging.

**Comment by jethror1** [comment]
Was this or similar methods ever implemented to modify VCF headers? It would be great if I could do this through pysam instead of having to manually read out the header and modify myself.

Use case for me is some types for INFO fields are wrongly set to strings, and I need to set these to floats but can't currently do this with pysam as an AssertionError is raised.
