### ISSUE TITLE
fetch using region string doesn't work for contigs with '-' in the name

### ISSUE THREAD

**Issue by kmhernan** [pysam-developers/pysam#673]
I'm pretty sure the culprit is the splitting section here https://github.com/pysam-developers/pysam/blob/master/pysam/libchtslib.pyx#L656-L657

For example:

```
>>> region = 'HCV-1:9400-9500'
>>> re.split('[:-]', region)
['HCV', '1', '9400', '9500']
>>> parts = re.split('[:-]', region)
>>> contig = parts[0]
>>> contig
'HCV'
```

And in pysam fetch:

```
>>> vfil.fetch(region='HCV-1:9400-9500')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/libcbcf.pyx", line 4342, in pysam.libcbcf.VariantFile.fetch
  File "pysam/libchtslib.pyx", line 675, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `HCV`
```

But I can do it outside of the region string:

```
>>> list(vfil.fetch('HCV-1', 9400, 9500))
[<pysam.libcbcf.VariantRecord object at 0x7fee797356d8>]
```

**Comment by AndreasHeger** [comment]
Thanks, good point.

**Comment by kmhernan** [comment]
I think I saw similar errors
