### ISSUE TITLE
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 72, got 48

### ISSUE THREAD

**Issue by kevinrue** [pysam-developers/pysam#687]
Dear Andreas,

I hope I'm not missing anything obvious, but I think I have a possible follow-up on #634 

```
$ cgat bam2bam --help
Traceback (most recent call last):
  File "/gfs/devel/kralbrecht/cgat/CGAT/scripts/bam2bam.py", line 159, in <module>
    import _bam2bam
ModuleNotFoundError: No module named '_bam2bam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gfs/devel/kralbrecht/python3-venv-3.6.2/bin/cgat", line 11, in <module>
    load_entry_point('CGAT', 'console_scripts', 'cgat')()
  File "/gfs/devel/kralbrecht/cgat/CGAT/cgat.py", line 129, in main
    module = imp.load_module(command, file, pathname, description)
  File "/gfs/apps/apps/python-3.6.2/lib/python3.6/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/gfs/apps/apps/python-3.6.2/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/gfs/devel/kralbrecht/cgat/CGAT/scripts/bam2bam.py", line 161, in <module>
    import CGAT.scripts._bam2bam as _bam2bam
  File "libcalignedsegment.pxd", line 63, in init CGAT.scripts._bam2bam
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 72, got 48
```

I've `git pull` and `python setup.py develop` the `git@github.com:CGATOxford/cgat.git` repository.
It did update a lot of things, but I still get the same error as above.

I can reproduce the same issue at the Python prompt:
```
$ python
Python 3.6.2 (default, Sep 25 2017, 19:31:23) 
[GCC 5.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import CGAT.scripts._bam2bam as _bam2bam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "libcalignedsegment.pxd", line 63, in init CGAT.scripts._bam2bam
ValueError: pysam.libcalignedsegment.PileupColumn has the wrong size, try recompiling. Expected 72, got 48
```

Note that I saw those two warnings:
```
$ python setup.py develop > log
warning: no files found matching 'CGAT/scripts/cgat.py'
warning: no files found matching 'CGAT/scripts/version.py'
```

Also:
```
>>> import pysam
>>> pysam.__version__
'0.14.1'
```

Best,
Kevin

**Comment by kevinrue** [comment]
For a moment, I forgot I had seen that same issue before:

Considering that I'm an older version of the CGAT code for this project, my workaround is to currently downgrade to `pip install pysam==0.13`

Sorry for the confusion between CGAT code and pysam here.
