### ISSUE TITLE
headers assumed to be ascii encoded 

### ISSUE THREAD

**Issue by snsansom** [pysam-developers/pysam#688]
So, with python3 pysam attempts to decode all headers as 'ascii' encoded strings which is not necessarily true:

`
>>> import pysam
>>> pysam.__version__
'0.14.1'
>>> locale.getpreferredencoding(False)
'UTF-8'
>>> cram = pysam.AlignmentFile("data.dir/21653_3#270.cram", "rc")
>>> cram.header
<pysam.libcalignmentfile.AlignmentHeader object at 0x7f62e0793ab0>
>>> print(cram.header)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/libcalignmentfile.pyx", line 530, in pysam.libcalignmentfile.AlignmentHeader.__str__
  File "pysam/libcutils.pyx", line 90, in pysam.libcutils.from_string_and_size
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 548: ordinal not in range(128)
`

and see libcutils.pyx lines 88-92:
`
cdef from_string_and_size(const char* s, size_t length):
    if IS_PYTHON3:
        return s[:length].decode("ascii")
    else:
        return s[:length]
`

Not sure how best this should be fixed? Perhaps pysam.AlignmentFile could accept an "encoding" argument?

**Comment by snsansom** [comment]
For reference, here is the current behaviour under python2:

```
$ python
Python 2.7.13 (default, Mar  7 2017, 14:23:09) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
>>> pysam.__version__
'0.14.1'
>>> cram = pysam.AlignmentFile("data.dir/21653_3#270.cram", "rc")
>>> cram.header
<pysam.libcalignmentfile.AlignmentHeader object at 0x7f90c83f81b0>
>>> print(cram.header)
@HD	VN:1.4	SO:coordinate
...
```

**Comment by AndreasHeger** [comment]
Hi @snsansom, 

thanks, spec v1.6 does allow UTF-8 in some header tags, will need to implement this.

please also see @445.
