### ISSUE TITLE
Error in running pbtranscript classify (isoseq2)

### ISSUE THREAD

**Issue by upendrak** [pysam-developers/pysam#691]
For some reason, eventhough the pysam is installed, I am getting this error and I don't understand why and what is the error is. Can someone help me with this?

```
pbtranscript classify -h
Traceback (most recent call last):
  File "/opt/pacbio/bin/pbtranscript", line 11, in <module>
    load_entry_point('pbtranscript==1.0.0', 'console_scripts', 'pbtranscript')()
  File "/opt/pacbio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/pacbio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/opt/pacbio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/opt/pacbio/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/pacbio/lib/python2.7/site-packages/pbtranscript/PBTranscriptRunner.py", line 41, in <module>
    from pbtranscript.Classifier import Classifier, ChimeraDetectionOptions
  File "/opt/pacbio/lib/python2.7/site-packages/pbtranscript/Classifier.py", line 12, in <module>
    from pbcore.io import FastaWriter
  File "/opt/pacbio/lib/python2.7/site-packages/pbcore/io/__init__.py", line 39, in <module>
    from .align   import *
  File "/opt/pacbio/lib/python2.7/site-packages/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/opt/pacbio/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 38, in <module>
    from pysam.libcalignmentfile import AlignmentFile # pylint: disable=no-name-in-module, import-error, fixme, line-too-long
  File "/opt/pacbio/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /opt/pacbio/lib/python2.7/site-packages/pysam/libchtslib.so: undefined symbol: inflate
```

**Comment by kyleabeauchamp** [comment]
IMOH, this has to do with the linker not being able to find zlib.

Are you using the Bioconda packages?  In the very latest bioconda packages, we're using libdeflate as a faster alternative to zlib, although I'm not sure that impacts the version you're using.

**Comment by upendrak** [comment]
I am not using Bioconda for installing any of the dependencies for Isoseq2. Just regular pip installs of the dependencies. How do I fix with the zlib issue then? Any ideas? Thanks

**Comment by kyleabeauchamp** [comment]
It may be that your sysadmin needs to install zlib.  Not sure.

**Comment by upendrak** [comment]
zlib is already installed on my system

**Comment by AndreasHeger** [comment]
Agree, is likely to be a linking issue. Is it still a problem?

**Comment by upendrak** [comment]
I found an alternative to `pbscript classify` script and I am using it - https://github.com/PacificBiosciences/IsoSeq3. I can close this if you want..

**Comment by AndreasHeger** [comment]
Thanks , good to hear, closing.
