### ISSUE TITLE
AttributeError: module 'pysam' has no attribute 'BAM_CINS'

### ISSUE THREAD

**Issue by Coaxecva** [pysam-developers/pysam#692]
Hi,
I tried to use pysam.BAM_CINS and other constant values like 'CIGAR_OPS', however, it said AttributeEror. Wonder if I used them the correct way?
Thanks,
Quang

~~~~python
>>> import pysam
>>> pysam.__version__
'0.14.1'
>>> pysam.BAM_CMATCH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pysam' has no attribute 'BAM_CMATCH'
>>> pysam.BAM_CINS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pysam' has no attribute 'BAM_CINS'
~~~~

**Comment by AndreasHeger** [comment]
Hi, pysam.CINS should work:
```
python -c 'import pysam; print(pysam.CINS)'
CIGAR_OPS.CINS
```
Closing this issue for now, please reopen if it does not work.
