### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by KidneyPunch** [pysam-developers/pysam#740]
I know this is a known issue, but I don't see it here for Windows 10 users with Python 3.7.
Using Anaconda and `pip install nanopack` the process collects all the packages, then I get the following error:

_(not showing previously fetched packages to save space, but they all fetched similar to NanoGUI)_
```
Collecting NanoGUI (from nanopack)
  Using cached https://files.pythonhosted.org/packages/bd/a1/6cf74f2086e4e7215c740c28671337f01d126e9d2f4ec6ebacc47fd792de/NanoGUI-0.1.0.tar.gz
Requirement already satisfied: biopython in c:\programdata\anaconda3\lib\site-packages (from NanoPlot>=0.20.1->nanopack) (1.72)
Collecting pysam>0.10.0.0 (from NanoPlot>=0.20.1->nanopack)
  Using cached https://files.pythonhosted.org/packages/73/59/c319f1bde3019bbce4583cecb12b9e3e52ffcfbe2c96d8b1fb131c0d4fb7/pysam-0.15.1.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: cython is available - using cythonize if necessary
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mlsyring\AppData\Local\Temp\pip-install-h3benh6k\pysam\setup.py", line 223, in <module>
        htslib_make_options = run_make_print_config()
      File "C:\Users\mlsyring\AppData\Local\Temp\pip-install-h3benh6k\pysam\setup.py", line 69, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 389, in check_output
        **kwargs).stdout
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 466, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 769, in __init__
        restore_signals, start_new_session)
      File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1172, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mlsyring\AppData\Local\Temp\pip-install-h3benh6k\pysam\
```

I updated setuptools (as other forums mentioned) with `pip install --upgrade setuptools`, but I still get the error.  Any idea how to fix this?  I can get other packages to install, just not nanopack.

**Comment by garrettjstevens** [comment]
I think in general pysam does not support Windows. See https://github.com/pysam-developers/pysam/issues/575.
