### ISSUE TITLE
Support for serialization?

### ISSUE THREAD

**Issue by llevar** [pysam-developers/pysam#752]
Hello,

I've run into a roadblock using pysam objects (AlignedSegment) with Apache Spark. Distributing objects across the network requires the ability to serialize them via pickle. It looks like serialization of most pysam objects is not supported. Any particular reason why not? When I try to serialize via dill, dill.dumps() appears to work, but when I dill.loads() it causes a seg fault. 

"Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

It would be great if serialization was supported, not just for Spark but any other parallel processing libraries.

**Comment by arogozhnikov** [comment]
+1 for this issue. So far my best shot is to convert to dictionary. I see no other way to parallelize and aggregate reads.

**Comment by Poshi** [comment]
Another +1.
I'm trying to parallelize some other's code based on pysam, and now that I almost reworked everything, the code fails because an AlignedSegment cannot be pickled.
I'm aware of the `to_string` and `fromstring` methods, but going to that level means having to modify the whole suite of tools I'm working on. The pickling is being make automatically for me, so I have no option of telling the system I want to use those methods.
I also tried with `copyreg.pickle(pysam.AlignedSegment, pysam.AlignedSegment.to_string, pysam.AlignedSegment.fromstring)`, but it also fails:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in pysam.libcalignedsegment.AlignedSegment.__reduce_cython__
TypeError: self._delegate cannot be converted to a Python object for pickling
```
Having pickability out of the box will solve many issues for the poor ones that try to parallelize bam-related problems.
