### ISSUE TITLE
Exception running with pypy

### ISSUE THREAD

**Issue by leecbaker** [pysam-developers/pysam#790]
I'm currently trying to use pypy in a project that depends on pysam. Importing pysam immediately triggers an exception- is there something that can be done to fix this?

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lee/othram/bam_report/pypyvenv/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "array.pxd", line 58, in init pysam.libchtslib
ValueError: array.array has the wrong size, try recompiling. Expected 24, got 72
```

**Comment by reece** [comment]
# Error
When importing PySAM 0.16.0.1 in pypy3, I get  `ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject`  

# Platform
- Ubuntu 20.04
- pypy3 (python 2.6.9) installed with apt
- PySAM 0.16.0.1 installed with pip

# Steps to reproduce
```
$ sudo apt install pypy3 pypy3-dev
$ pypy3 -m venv venv/pypy3
$ source venv/pypy3/bin/activate
$ pip install -U pip setuptools wheel
$ pip install pysam
$ python -m pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reece/venv/pypy3/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject
```

**Comment by jmarshall** [comment]
Pysam uses `from cpython cimport array` in several of its source files. As the name suggests, Cython's policy is that this works with CPython only and is not compatible with PyPy, as you've experienced. See cython/cython#1818 and cython/cython#3448.

Use of `cpython.array` is fairly ingrained in some parts of pysam. So at present pysam is not compatible with PyPy. It would be possible to recode this functionality eventually:

* Now that pysam is Python-3-only, perhaps the native facilities [described here](https://cython.readthedocs.io/en/latest/src/userguide/memoryviews.html?highlight=cpython.array#cpython-array-module) would suffice;
* Or we could follow h5py/h5py#1515's approach of rewriting this using `char *`.
