### ISSUE TITLE
No index available for pileup with stdin

### ISSUE THREAD

**Issue by dariober** [pysam-developers/pysam#810]
Hi- Processing a bam file from `stdin` using the pileup engine I get `ValueError: no index available for pileup`. The relevant bit of code:

```
samfile= pysam.AlignmentFile("-")
pileup= samfile.pileup()
for column in pileup:
    print(column.nsegments)
```

Executed as `samtools view -u my.bam | remove_bam_background.py`:

```
Traceback (most recent call last):
  File "/export/.../remove_bam_background.py", line 34, in <module>
    pileup= samfile.pileup()
  File "pysam/libcalignmentfile.pyx", line 1330, in pysam.libcalignmentfile.AlignmentFile.pileup
ValueError: no index available for pileup
```

This is with python 3.6 and pysam 0.15.2.

This issue is a duplicate of and old post at https://groups.google.com/forum/#!topic/pysam-user-group/eyXW35Fpwnc 

I wonder if there is anything that could be done to fix it...? Thanks!

**Comment by tdreal** [comment]
I am having a similar issue! I am trying to use STDIN with fetch() and bam files that definitely have 
indexes in the same location. When I include the file in the code, it has no issue finding the index.

```
import sys
import pysam
import matplotlib.pyplot as plt
myReader = pysam.AlignmentFile('filename.bam', 'rb')
mapQual = []
for read in myReader.fetch('NOTCH2NL-consensus', 103370, 103630):
    addMQ = mapQual.append(read.mapping_quality) 

```
but when the code is written with  the STDIN  '-'

```
import sys
import pysam
import matplotlib.pyplot as plt
myReader = pysam.AlignmentFile('-', 'rb')
mapQual = []
for read in myReader.fetch('NOTCH2NL-consensus', 103370, 103630):
    addMQ = mapQual.append(read.mapping_quality) 


```
I receive the following error:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    for read in myReader.fetch('NOTCH2NL-consensus', 103370, 103630):
  File "pysam/libcalignmentfile.pyx", line 1087, in pysam.libcalignmentfile.AlignmentFile.fetch
ValueError: fetch called on bamfile without index
```
I have remade the index files multiple times, so I know that's probably not the issue. Is there a way to fix this?

**Comment by dariober** [comment]
@tdreal I don't think your issue is the same as the one I report. I'm trying to generate the pileup at every position in input so the index should not be necessary. What I'm trying to do is the same as:

```
samtools view -u my.bam | samtools mpileup -
``` 

Instead, you want a pileup in a specific region and for this you do need the index to jump at that position. It is equivalent to:

```
samtools view -u my.bam | samtools mpileup -r NOTCH2NL-consensus:103370-103630 -
[mpileup] fail to load index for -
```
