### ISSUE TITLE
pileup doesn't work on python3 when `index_filename` explicitly specified

### ISSUE THREAD

**Issue by VorontsovIE** [pysam-developers/pysam#840]
Try this simple example:
```
import pysam

bam_fn = "tst.bam"
pysam.index(bam_fn)
index_fn = "tst.bam.bai"

samfile = pysam.AlignmentFile(bam_fn, "rb", index_filename=index_fn)

for _ in samfile.pileup('ENSMUST00000000001.4'):
    pass
```

It works good with python2, but python3 fails (as of version 0.15.3) with the following error:
```
Traceback (most recent call last):
  File "tst.py", line 9, in <module>
    for _ in samfile.pileup('ENSMUST00000000001.4'):
  File "pysam/libcalignmentfile.pyx", line 1338, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libcalignmentfile.pyx", line 2625, in pysam.libcalignmentfile.IteratorColumnRegion.__cinit__
  File "pysam/libcalignmentfile.pyx", line 2508, in pysam.libcalignmentfile.IteratorColumn._setup_iterator
  File "pysam/libcalignmentfile.pyx", line 2061, in pysam.libcalignmentfile.IteratorRowRegion.__init__
  File "pysam/libcalignmentfile.pyx", line 2000, in pysam.libcalignmentfile.IteratorRow.__init__
TypeError: expected bytes, str found
```

When I remove explicit `index_filename` argument from `AlignmentFile` constructor, everything works both in python2 and python3.

**Comment by isthisthat** [comment]
I get the same error, only in python3,  when I specify an `index_filename` and call `read2 = bamFile.mate(read)`. Probably related
