### ISSUE TITLE
pysam error: libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

### ISSUE THREAD

**Issue by Benfeitas** [pysam-developers/pysam#844]
I keep getting the error

    libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

For instance when I run 

    python -c "import pysam; print(pysam.__version__)"

How can I fix this? Can't find anything on this error. Thanks in advance

**Comment by Benfeitas** [comment]
Related: https://github.com/shunping/lapels/issues/1

**Comment by mobiusklein** [comment]
Can you verify that the version of Python you're using is the same version that `pysam` was built against? That error message suggests different PyUnicode APIs are present at run time vs. build time.

**Comment by AnneJRomero** [comment]
Hi, 

I am getting the same error. I'm running jitterbug (https://github.com/elzbth/jitterbug) which requires pysam to run 

Traceback (most recent call last):
  File "./jitterbug.py", line 21, in <module>
    from Run_TE_ID_reseq import *
  File "/mainfs/scratch/ar14g12/PhD/tomato/TE/jitterbug/jitterbug/Run_TE_ID_reseq.py", line 6, in <module>
    import pysam
  File "/home/ar14g12/.local/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/ar14g12/.local/lib/python2.7/site-packages/pysam/libchtslib.so: undefined symbol: PyUnicodeUCS2_DecodeUTF8

I have to use python2.7 to run jitterbug and I have pysam version 0.17.0 which should support that. 

Can you help with this error?

Thanks.
