### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by PlatonB** [pysam-developers/pysam#869]
elementary OS 5.1
HTSlib 1.9
pysam 0.15.3

`export HTSLIB_INCLUDE_DIR=/home/some_path/htslib/include/`
`export LD_LIBRARY_PATH=/home/some_path/htslib/lib/`
`pip3 install pysam --user`

`import pysam`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/platon/.local/lib/python3.6/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /home/platon/.local/lib/python3.6/site-packages/pysam/libchtslib.cpython-36m-x86_64-linux-gnu.so: undefined symbol: hts_utell

**Comment by mickeykawai** [comment]
The same error with source build of pysam 0.15.3 with python 3.8.1 (with htslib 1.10.2-6-g9369f1c). 
With python 3.7.6, no such error occurred, with pysam 0.15.3 and htslib 1.10.2-6-g9369f1c.

**Comment by brobr** [comment]
Hi, I ran into this while still on 0.15.3. Downloaded and installed 0.15.4 via a building script I maintain for Slackbuilds.org but still the same error is thrown:
(on Slackware64 current, python3.8.1; Cython-0.29.14; htslib-1.10.2)

` 
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /usr/lib64/python3.8/site-packages/pysam/libchtslib.cpython-38-x86_64-linux-gnu.so: undefined symbol: hts_utell
>>> 
`

**Comment by brobr** [comment]
The error came from using a shared htslib-1.10.2 instead of the bundled 0.9, which this version of pysam still depends on (that's why I closed issue #889)

**Comment by jmarshall** [comment]
Since 7b188499569083572c6421514583c9620f68feb5 (released in v0.16.0), pysam no longer uses `hts_utell()` directly.
