### ISSUE TITLE
import in pypy3 raises "ValueError: array.array size changed, may indicate binary incompatibility."

### ISSUE THREAD

**Issue by reece** [pysam-developers/pysam#952]
# Error
When importing PySAM 0.16.0.1 in pypy3, I get  `ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject`  

# Platform
- Ubuntu 20.04
- pypy3 (python 2.6.9) installed with apt
- PySAM 0.16.0.1 installed with pip

# Steps to reproduce
```
$ sudo apt install pypy3 pypy3-dev
$ pypy3 -m venv venv/pypy3
$ source venv/pypy3/bin/activate
$ pip install -U pip setuptools wheel
$ pip install pysam
$ python -m pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/reece/venv/pypy3/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
  File "pysam/libchtslib.pyx", line 1, in init pysam.libchtslib
ValueError: array.array size changed, may indicate binary incompatibility. Expected 72 from C header, got 24 from PyObject
```

**Comment by reece** [comment]
Whoops. Duplicate of #790. I'll tack on there.
