### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam.libchtslib'

### ISSUE THREAD

**Issue by zaneChou1** [pysam-developers/pysam#976]
Dear owner,

I've been trying to install pysam from pysam-v0.16.0.1.tar.gz for Python 3.7.6 ,  and the installation succeed:
```
$ python setup.py install:
......
Installed /opt/conda/lib/python3.7/site-packages/pysam-0.16.0.1-py3.7-linux-aarch64.egg
Processing dependencies for pysam==0.16.0.1
Finished processing dependencies for pysam==0.16.0.1
```
But, when I try to import pysam, I get the error:
```
Python 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:25:07)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysam
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/pkg/pysam-0.16.0.1/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ModuleNotFoundError: No module named 'pysam.libchtslib'
```

my cython version is ` Cython version 0.29.21`

I do not know how to fix this problem.

Thanks for any help!

**Comment by brianpenghe** [comment]
same problem here

**Comment by chairchild** [comment]
cython version 0.29.28. pysam version 0.16.01. same problem

**Comment by chairchild** [comment]
you can try add pysam to your enviroment PYTHONPATH. but it's not work for me.

**Comment by 120L021101** [comment]
I found the same problem, then I directly run "pip install pysam==0.16.0" and found it was OK. my pip version is 19.0 and python version is 2.7. Hope it can help you :).
